export type Size = 'Pequeno' | 'Médio' | 'Grande';

export type DogData = {
  id: number;
  slug: string;
  breed: string;
  image: string;
  size: Size;
  countryOrigin: string;
  colors: string[];
  lifeExpectancy: { min: number; max: number };
  adultWeightKg: {
    male: { min: number; max: number };
    female: { min: number; max: number }
  };
  classification: string[];
  description: string;
};

export const dogsData: DogData[] = [
  {
    id: 1,
    slug: "labrador-retriever",
    breed: "Labrador Retriever",
    image: "v1777845035/dogs/ayp1ygq1vzx0ksgtnzyk.jpg",
    size: "Médio",
    countryOrigin: "Canadá",
    colors: ["Preto", "Marrom", "Caramelo"],
    lifeExpectancy: { min: 10, max: 12 },
    adultWeightKg: { male: { min: 29, max: 36 }, female: { min: 25, max: 32 } },
    classification: ["Companhia", "Assistência"],
    description: "O Labrador é dócil, brincalhão e inteligente, ideal para famílias ativas. Vive bem em casas com quintal e adora água e brincadeiras ao ar livre."
  },
  {
    id: 2,
    slug: "golden-retriever",
    breed: "Golden Retriever",
    image: "v1777845031/dogs/ayup8xovbrplcghurtwm.jpg",
    size: "Médio",
    countryOrigin: "Escócia",
    colors: ["Dourado"],
    lifeExpectancy: { min: 10, max: 12 },
    adultWeightKg: { male: { min: 29, max: 34 }, female: { min: 25, max: 29 } },
    classification: ["Companhia", "Assistência"],
    description: "O Golden é afetuoso, calmo e excelente com crianças. Se adapta a espaços maiores e precisa de exercícios diários para manter a saúde física e mental."
  },
  {
    id: 3,
    slug: "poodle",
    breed: "Poodle",
    image: "v1777845044/dogs/tnagugtzuwlulhg7fxng.jpg",
    size: "Pequeno",
    countryOrigin: "Alemanha/França",
    colors: ["Branco", "Preto", "Marrom", "Cinza", "Dourado", "Laranja"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 6, max: 12 }, female: { min: 6, max: 10 } },
    classification: ["Companhia", "Competições de agilidade"],
    description: "O Poodle é inteligente, hipoalergênico e aprende comandos com facilidade. Ideal para apartamentos, desde que tenha estímulos mentais e caminhadas regulares."
  },
  {
    id: 4,
    slug: "bulldog-frances",
    breed: "Bulldog Francês",
    image: "v1777845018/dogs/tjv1geepxvp5vzbh66x0.jpg",
    size: "Pequeno",
    countryOrigin: "França",
    colors: ["Tigrado", "Preto", "Branco", "Cinza"],
    lifeExpectancy: { min: 10, max: 12 },
    adultWeightKg: { male: { min: 9, max: 14 }, female: { min: 8, max: 12 } },
    classification: ["Companhia"],
    description: "Afetuoso e tranquilo, o Bulldog Francês adora companhia humana. Vive muito bem em apartamentos, mas exige atenção por causa de problemas respiratórios."
  },
  {
    id: 5,
    slug: "bulldog-ingles",
    breed: "Bulldog Inglês",
    image: "v1777845019/dogs/omqjp88dbd6earsgkov0.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Branco", "Caramelo", "Tigrado", "Vermelho"],
    lifeExpectancy: { min: 8, max: 10 },
    adultWeightKg: { male: { min: 23, max: 25 }, female: { min: 18, max: 23 } },
    classification: ["Companhia"],
    description: "O Bulldog Inglês é calmo e companheiro, ideal para lares tranquilos. Adapta-se bem a apartamentos, mas requer cuidados com calor e exercícios leves."
  },
  {
    id: 6,
    slug: "pastor-alemao",
    breed: "Pastor Alemão",
    image: "v1777845040/dogs/u58t4isbd98ounhgegpi.jpg",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Preto e marrom", "Cinza", "Preto"],
    lifeExpectancy: { min: 9, max: 13 },
    adultWeightKg: { male: { min: 30, max: 40 }, female: { min: 22, max: 32 } },
    classification: ["Guarda", "Resgate", "Companhia"],
    description: "Leal, protetor e inteligente, o Pastor Alemão é excelente para guarda e resgate. Precisa de espaço e atividades, sendo mais adequado a casas com quintal ou áreas abertas."
  },
  {
    id: 7,
    slug: "beagle",
    breed: "Beagle",
    image: "v1777845015/dogs/f2fndkclntjsjcy2ru6u.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Marrom", "Branco", "Preto", "Tricolor"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 10, max: 14 }, female: { min: 9, max: 12 } },
    classification: ["Caça", "Companhia"],
    description: "O Beagle é curioso, sociável e enérgico. Se adapta a casas e apartamentos com rotina ativa, mas requer atenção por seu faro aguçado e tendência a fugir."
  },
  {
    id: 8,
    slug: "rottweiler",
    breed: "Rottweiler",
    image: "v1777845046/dogs/h9rut6q2arts9kqa3m1y.jpg",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Preto e marrom"],
    lifeExpectancy: { min: 8, max: 10 },
    adultWeightKg: { male: { min: 50, max: 60 }, female: { min: 35, max: 48 } },
    classification: ["Guarda", "Companhia"],
    description: "O Rottweiler é forte, leal e protetor. Ideal para casas com espaço e donos experientes; precisa de socialização e adestramento desde cedo."
  },
  {
    id: 9,
    slug: "yorkshire-terrier",
    breed: "Yorkshire Terrier",
    image: "v1777845054/dogs/nkbb6lt2nzedh1bigtba.jpg",
    size: "Pequeno",
    countryOrigin: "Reino Unido",
    colors: ["Cinza", "Dourado", "Preto"],
    lifeExpectancy: { min: 13, max: 16 },
    adultWeightKg: { male: { min: 2, max: 3 }, female: { min: 2, max: 3 } },
    classification: ["Companhia"],
    description: "Pequeno, valente e elegante, o Yorkshire é ótimo para apartamentos. Precisa de escovação frequente e adora estar no colo do tutor."
  },
  {
    id: 10,
    slug: "shih-tzu",
    breed: "Shih Tzu",
    image: "v1777845050/dogs/ijrsu1i5tdvwl8fgi9wk.jpg",
    size: "Pequeno",
    countryOrigin: "China",
    colors: ["Branco", "Marrom", "Preto", "Dourado", "Cinza"],
    lifeExpectancy: { min: 10, max: 16 },
    adultWeightKg: { male: { min: 4, max: 7 }, female: { min: 4, max: 7 } },
    classification: ["Companhia"],
    description: "O Shih Tzu é dócil, sociável e muito apegado à família. Ideal para apartamentos, exige cuidados com os pelos e olhos sensíveis."
  },
  {
    id: 11,
    slug: "border-collie",
    breed: "Border Collie",
    image: "v1777845016/dogs/mwsvbrhp7mayo5njg0g3.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Preto e branco", "Tricolor", "Marrom e branco"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 16, max: 20 }, female: { min: 14, max: 18 } },
    classification: ["Assistência", "Companhia"],
    description: "Extremamente inteligente e ágil, o Border Collie é ideal para quem mora no campo ou tem espaço para atividades intensas. Não se adapta bem à vida sedentária."
  },
  {
    id: 12,
    slug: "dachshund",
    breed: "Dachshund",
    image: "v1777845024/dogs/xvi8qjmi9retqo6y7ttl.jpg",
    size: "Pequeno",
    countryOrigin: "Alemanha",
    colors: ["Marrom", "Preto e marrom", "Vermelho", "Tigrado"],
    lifeExpectancy: { min: 12, max: 16 },
    adultWeightKg: { male: { min: 7, max: 14 }, female: { min: 7, max: 12 } },
    classification: ["Caça", "Companhia"],
    description: "Destemido e divertido, o Dachshund adora cavar e seguir trilhas. Vive bem em apartamentos, mas precisa de cuidados com a coluna e caminhadas leves."
  },
  {
    id: 13,
    slug: "boxer",
    breed: "Boxer",
    image: "v1777845018/dogs/tjv1geepxvp5vzbh66x0.jpg",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Caramelo", "Tigrado", "Branco"],
    lifeExpectancy: { min: 10, max: 12 },
    adultWeightKg: { male: { min: 28, max: 32 }, female: { min: 25, max: 29 } },
    classification: ["Guarda", "Companhia"],
    description: "O Boxer é brincalhão, fiel e cheio de energia. Ideal para casas com quintal e tutores que gostam de atividades ao ar livre."
  },
  {
    id: 14,
    slug: "doberman",
    breed: "Doberman",
    image: "v1777845025/dogs/qefokvlrtl0b2mpu7fth.webp",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Preto e marrom", "Marrom", "Azul"],
    lifeExpectancy: { min: 10, max: 13 },
    adultWeightKg: { male: { min: 40, max: 45 }, female: { min: 30, max: 35 } },
    classification: ["Guarda", "Companhia"],
    description: "Elegante, protetor e obediente, o Doberman é ótimo para guarda. Requer espaço, liderança firme e atenção constante."
  },
  {
    id: 15,
    slug: "husky-siberiano",
    breed: "Husky Siberiano",
    image: "v1777845032/dogs/add7zxqilp9rhm7hrg9o.jpg",
    size: "Grande",
    countryOrigin: "Rússia",
    colors: ["Cinza", "Preto e branco", "Vermelho", "Branco"],
    lifeExpectancy: { min: 12, max: 14 },
    adultWeightKg: { male: { min: 23, max: 27 }, female: { min: 16, max: 23 } },
    classification: ["Companhia", "Competições de agilidade"],
    description: "Independente e energético, o Husky adora correr e é sensível ao calor. Prefere ambientes frios e espaços amplos, como casas com quintal."
  },
  {
    id: 16,
    slug: "chihuahua",
    breed: "Chihuahua",
    image: "v1777845021/dogs/khtfa4v5tigcpmpv2wty.png",
    size: "Pequeno",
    countryOrigin: "México",
    colors: ["Marrom", "Preto", "Branco", "Dourado", "Mesclado"],
    lifeExpectancy: { min: 14, max: 17 },
    adultWeightKg: { male: { min: 1.5, max: 3 }, female: { min: 1.5, max: 3 } },
    classification: ["Companhia"],
    description: "Pequeno e alerta, o Chihuahua é ideal para apartamentos e tutores tranquilos. Gosta de colo, mas pode ser desconfiado com estranhos."
  },
  {
    id: 17,
    slug: "pug",
    breed: "Pug",
    image: "v1777845045/dogs/qfg3ag8uyoskzjogqf0t.jpg",
    size: "Pequeno",
    countryOrigin: "China",
    colors: ["Caramelo", "Preto", "Cinza", "Bege"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 6, max: 9 }, female: { min: 6, max: 8 } },
    classification: ["Companhia"],
    description: "Afetuoso e divertido, o Pug é perfeito para apartamentos. Requer atenção com a respiração e não tolera muito calor ou exercícios intensos."
  },
  {
    id: 18,
    slug: "vira-lata",
    breed: "Vira-lata",
    image: "v1777845051/dogs/c8k2o3wxbcfrfzzolqbp.jpg",
    size: "Médio",
    countryOrigin: "Brasil",
    colors: ["Preto", "Caramelo", "Branco", "Mesclado"],
    lifeExpectancy: { min: 12, max: 16 },
    adultWeightKg: { male: { min: 12, max: 25 }, female: { min: 10, max: 20 } },
    classification: ["Companhia", "Guarda"],
    description: "Versátil, resistente e amoroso, o Vira-lata se adapta bem a diferentes ambientes. Cada um tem uma personalidade única, ideal para quem busca um companheiro fiel."
  },
  {
    id: 19,
    slug: "cocker-spaniel",
    breed: "Cocker Spaniel",
    image: "v1777845023/dogs/zzmfzzu4vxe3g4yvf7pd.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Dourado", "Preto", "Marrom", "Tricolor", "Azul"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 13, max: 15 }, female: { min: 12, max: 14 } },
    classification: ["Caça", "Companhia"],
    description: "Meigo e sociável, o Cocker é ótimo para crianças e vive bem em apartamentos ou casas. Precisa de escovação frequente e passeios diários."
  },
  {
    id: 20,
    slug: "maltes",
    breed: "Maltês",
    image: "v1777845037/dogs/oflbmfefmihc4368eni7.jpg",
    size: "Pequeno",
    countryOrigin: "Itália",
    colors: ["Branco"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 3, max: 4 }, female: { min: 3, max: 4 } },
    classification: ["Companhia"],
    description: "Delicado e muito apegado, o Maltês se adapta bem a apartamentos. Seus pelos exigem escovação constante, e ele adora colo e atenção."
  },
  {
    id: 21,
    slug: "fila-brasileiro",
    breed: "Fila Brasileiro",
    image: "v1777845028/dogs/g6sxqi5tbanlosdm5kx0.jpg",
    size: "Grande",
    countryOrigin: "Brasil",
    colors: ["Caramelo", "Tigrado", "Preto"],
    lifeExpectancy: { min: 9, max: 11 },
    adultWeightKg: { male: { min: 50, max: 60 }, female: { min: 40, max: 50 } },
    classification: ["Guarda", "Caça"],
    description: "Imponente e territorialista, o Fila exige espaço, adestramento e socialização. Ideal para grandes propriedades e tutores experientes."
  },
  {
    id: 22,
    slug: "fox-paulistinha",
    breed: "Fox Paulistinha",
    image: "v1777845030/dogs/iambjenav85rkzoucy9u.jpg",
    size: "Médio",
    countryOrigin: "Brasil",
    colors: ["Tricolor"],
    lifeExpectancy: { min: 13, max: 16 },
    adultWeightKg: { male: { min: 7, max: 10 }, female: { min: 6, max: 9 } },
    classification: ["Companhia", "Competições de agilidade"],
    description: "Ágil, leal e muito esperto, o Fox Paulistinha é ótimo para quem vive em casas ou apartamentos com rotina ativa. Ama brincar e aprender truques."
  },
  {
    id: 23,
    slug: "spitz-alemao",
    breed: "Spitz Alemão (Lulu da Pomerânia)",
    image: "v1777845051/dogs/xptptpmpblwknxdulvnw.jpg",
    size: "Pequeno",
    countryOrigin: "Alemanha",
    colors: ["Laranja", "Branco", "Preto", "Marrom", "Bege"],
    lifeExpectancy: { min: 12, max: 16 },
    adultWeightKg: { male: { min: 1.5, max: 3.5 }, female: { min: 1.5, max: 3 } },
    classification: ["Companhia"],
    description: "Pequeno, animado e muito apegado ao tutor, o Spitz Alemão é ideal para apartamentos. Gosta de atenção e cuidados com os pelos são essenciais para manter sua beleza."
  },
  {
    id: 24,
    slug: "pitbull-terrier-americano",
    breed: "Pitbull Terrier Americano",
    image: "v1777845043/dogs/ppchqueeqszgswvdsqj9.jpg",
    size: "Médio",
    countryOrigin: "Estados Unidos",
    colors: ["Preto", "Branco", "Caramelo", "Tigrado", "Cinza"],
    lifeExpectancy: { min: 12, max: 14 },
    adultWeightKg: { male: { min: 16, max: 30 }, female: { min: 14, max: 27 } },
    classification: ["Companhia", "Guarda"],
    description: "Forte, leal e inteligente, o Pitbull é um excelente companheiro para tutores firmes e ativos. Requer socialização desde cedo e vive melhor em casas com espaço para se exercitar."
  },
  {
    id: 25,
    slug: "dalmata",
    breed: "Dálmata",
    image: "v1777845025/dogs/wul8nde3xpkcymggifd2.png",
    size: "Médio",
    countryOrigin: "Croácia",
    colors: ["Preto e branco", "Marrom e branco"],
    lifeExpectancy: { min: 10, max: 13 },
    adultWeightKg: { male: { min: 24, max: 32 }, female: { min: 22, max: 28 } },
    classification: ["Companhia", "Guarda", "Caça"],
    description: "O Dálmata é um cão enérgico e extrovertido, famoso por sua pelagem manchada. Ele é excelente para famílias ativas e precisa de bastante exercício para se manter saudável e feliz. Seu instinto protetor e lealdade fazem dele um ótimo companheiro."
  },
  {
    id: 26,
    slug: "lhasa-apso",
    breed: "Lhasa Apso",
    image: "v1777845036/dogs/mmknefnihqgfnq5yg40o.jpg",
    size: "Pequeno",
    countryOrigin: "China",
    colors: ["Dourado", "Preto", "Branco", "Mesclado", "Cinza"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 6, max: 8 }, female: { min: 5, max: 7 } },
    classification: ["Companhia"],
    description: "Independente, calmo e protetor, o Lhasa Apso vive muito bem em apartamentos. Exige escovação frequente e costuma ser reservado com estranhos."
  },
  {
    id: 27,
    slug: "akita-inu",
    breed: "Akita Inu",
    image: "v1777845012/dogs/olbccr7nmnic9wfczbke.jpg",
    size: "Grande",
    countryOrigin: "Japão",
    colors: ["Vermelho", "Branco", "Tigrado", "Bege"],
    lifeExpectancy: { min: 10, max: 13 },
    adultWeightKg: { male: { min: 40, max: 50 }, female: { min: 30, max: 40 } },
    classification: ["Guarda", "Companhia"],
    description: "Silencioso, fiel e imponente, o Akita Inu é indicado para tutores experientes. Vive melhor em locais espaçosos e com socialização adequada desde filhote."
  },
  {
    id: 28,
    slug: "cao-de-crista-chines",
    breed: "Cão de Crista Chinês",
    image: "v1777845020/dogs/hos0wqhcwzifzdig1rsy.jpg",
    size: "Pequeno",
    countryOrigin: "China",
    colors: ["Rosa", "Cinza", "Preto", "Branco", "Manchado"],
    lifeExpectancy: { min: 13, max: 15 },
    adultWeightKg: { male: { min: 3, max: 6 }, female: { min: 3, max: 5 } },
    classification: ["Companhia"],
    description: "Exótico, brincalhão e afetuoso, o Cão de Crista Chinês é ideal para apartamentos e lares tranquilos. Exige cuidados com a pele, principalmente se for da variedade sem pelos."
  },
  {
    id: 29,
    slug: "weimaraner",
    breed: "Weimaraner",
    image: "v1777845052/dogs/i10u5rtmlnyfb9wdaniq.jpg",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Cinza"],
    lifeExpectancy: { min: 10, max: 13 },
    adultWeightKg: { male: { min: 30, max: 40 }, female: { min: 25, max: 35 } },
    classification: ["Caça", "Companhia"],
    description: "Elegante, atlético e inteligente, o Weimaraner precisa de muito exercício e estímulo mental. Vive melhor em casas com quintal e com tutores ativos."
  },
  {
    id: 30,
    slug: "sao-bernardo",
    breed: "São Bernardo",
    image: 'v1777845047/dogs/nh8ycc3fnuh9erkwkdy8.jpg',
    size: 'Grande',
    countryOrigin: 'Suíça',
    colors: ['Marrom e branco', 'Branco e vermelho', 'Tigrado'],
    lifeExpectancy: { min: 8, max: 10 },
    adultWeightKg: { male: { min: 65, max: 80 }, female: { min: 55, max: 70 } },
    classification: ['Guarda', 'Companhia', 'Resgate'],
    description: "Gentil, paciente e protetor, o São Bernardo é ideal para casas espaçosas ou zonas rurais. Apesar do tamanho imponente, é excelente com crianças, mas precisa de espaço, escovação regular e atenção ao calor."
  },
  {
    id: 31,
    slug: "pastor-belga",
    breed: "Pastor Belga",
    image: "v1777845041/dogs/fpeaz81xmzlsjpzgkem2.jpg",
    size: "Grande",
    countryOrigin: "Bélgica",
    colors: ["Preto", "Marrom", "Tigrado"],
    lifeExpectancy: { min: 12, max: 14 },
    adultWeightKg: { male: { min: 25, max: 30 }, female: { min: 25, max: 30 } },
    classification: ["Guarda", "Trabalho"],
    description: "O Pastor Belga é ágil, inteligente e muito leal. Usado em forças policiais, exige atividades físicas e mentais diárias."
  },
  {
    id: 32,
    slug: "pinscher-miniatura",
    breed: "Pinscher Miniatura",
    image: "v1777845042/dogs/pw8tgfyaapkj7zp3bbst.jpg",
    size: "Pequeno",
    countryOrigin: "Alemanha",
    colors: ["Preto e marrom", "Marrom", "Caramelo"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 3, max: 5 }, female: { min: 3, max: 5 } },
    classification: ["Companhia"],
    description: "Valente e energético, o Pinscher é um ótimo cão de alerta. Requer socialização desde filhote para evitar comportamento agressivo."
  },
  {
    id: 33,
    slug: "dogo-argentino",
    breed: "Dogo Argentino",
    image: "v1777845027/dogs/ocxto7elivpuoaj23seh.jpg",
    size: "Grande",
    countryOrigin: "Argentina",
    colors: ["Branco"],
    lifeExpectancy: { min: 10, max: 12 },
    adultWeightKg: { male: { min: 40, max: 45 }, female: { min: 40, max: 45 } },
    classification: ["Caça", "Guarda"],
    description: "O Dogo Argentino é uma raça forte e atlética, criada originalmente na Argentina para caça de animais grandes como javalis. É corajoso, leal e protetor, exigindo um tutor experiente, com socialização e adestramento desde cedo. Apesar de sua aparência intimidadora, pode ser afetuoso com a família."
  },
  {
    id: 34,
    slug: "boston-terrier",
    breed: "Boston Terrier",
    image: "v1777845017/dogs/evpdnubtib7tbtxn57ay.jpg",
    size: "Pequeno",
    countryOrigin: "Estados Unidos",
    colors: ["Preto e branco", "Tigrado", "Marrom e branco"],
    lifeExpectancy: { min: 11, max: 13 },
    adultWeightKg: { male: { min: 8, max: 11 }, female: { min: 6, max: 9 } },
    classification: ["Companhia"],
    description: "Afetuoso, brincalhão e sociável, o Boston Terrier se adapta bem a apartamentos e é ideal para famílias."
  },
  {
    id: 35,
    slug: "boiadeiro-australiano",
    breed: "Boiadeiro Australiano",
    image: "v1777845015/dogs/ywg5ikjrpnziaactcjqs.jpg",
    size: "Médio",
    countryOrigin: "Austrália",
    colors: ["Azul", "Vermelho"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 16, max: 22 }, female: { min: 14, max: 20 } },
    classification: ["Pastoreio", "Caça"],
    description: "Ágil, inteligente e muito resistente, o Boiadeiro Australiano é excelente para atividades no field e esportes caninos."
  },
  {
    id: 36,
    slug: "cane-corso",
    breed: "Cane Corso",
    image: "v1777845020/dogs/eeibgmcobcwceihwnnmz.jpg",
    size: "Grande",
    countryOrigin: "Itália",
    colors: ["Preto", "Cinza", "Tigrado", "Marrom"],
    lifeExpectancy: { min: 9, max: 12 },
    adultWeightKg: { male: { min: 45, max: 50 }, female: { min: 40, max: 45 } },
    classification: ["Guarda"],
    description: "Robusto e protetor, o Cane Corso é fiel à sua família. Precisa de adestramento firme e bastante espaço."
  },
  {
    id: 37,
    slug: "shar-pei",
    breed: "Shar Pei",
    image: "v1777845049/dogs/hs0kqxtcqul3fxmwcu1e.jpg",
    size: "Médio",
    countryOrigin: "China",
    colors: ["Bege", "Preto", "Marrom", "Azul"],
    lifeExpectancy: { min: 8, max: 12 },
    adultWeightKg: { male: { min: 20, max: 25 }, female: { min: 18, max: 23 } },
    classification: ["Companhia"],
    description: "Com rugas marcantes e personalidade reservada, o Shar Pei é calmo e fiel, mas precisa de socialização desde cedo."
  },
  {
    id: 38,
    slug: "kangal",
    breed: "Kangal",
    image: "v1777845033/dogs/n5opwfhufvvlk2vbpsaq.jpg",
    size: "Grande",
    countryOrigin: "Turquia",
    colors: ["Cinza", "Bege", "Caramelo", "Preto"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 50, max: 66 }, female: { min: 40, max: 55 } },
    classification: ["Guarda", "Caça", "Pastoreio"],
    description: "O Kangal é uma raça originária da Turquia, conhecida por sua força, coragem e instinto protetor. Tradicionalmente usado para proteger rebanhos, é extremamente leal à sua família. Apesar de seu tamanho imponente, é calmo, equilibrado e gentil."
  },
  {
    id: 39,
    slug: "whippet",
    breed: "Whippet",
    image: "v1777845053/dogs/xlqyiujkvzdasme9jtqe.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Preto", "Branco", "Tigrado", "Cinza", "Preto e branco"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 12, max: 15 }, female: { min: 10, max: 14 } },
    classification: ["Corrida", "Companhia"],
    description: "Rápido, sensível e elegante, o Whippet é ótimo para quem quer um cão calmo em casa, mas com energia para correr ao ar livre."
  },
  {
    id: 40,
    slug: "ovelheiro-gaucho",
    breed: "Ovelheiro Gaúcho",
    image: "v1777845038/dogs/yrbxlp5uuudl38exhsyi.jpg",
    size: "Grande",
    countryOrigin: "Brasil",
    colors: ["Preto", "Branco", "Cinza", "Azul", "Tricolor"],
    lifeExpectancy: { min: 13, max: 15 },
    adultWeightKg: { male: { min: 30, max: 40 }, female: { min: 25, max: 35 } },
    classification: ["Pastoreio", "Guarda", "Companhia"],
    description: "O Ovelheiro Gaúcho é uma raça brasileira, conhecida por sua inteligência, energia e forte instinto de pastoreio. Adaptado ao clima do sul do Brasil, é resistente, leal e excelente para trabalhar com rebanhos. Sociável com a família, mas pode ser reservado com estranhos."
  },
  {
    id: 41,
    slug: "schnauzer",
    breed: "Schnauzer",
    image: "v1777845048/dogs/fdrkuwwlgjutwioses34.jpg",
    size: "Médio",
    countryOrigin: "Alemanha",
    colors: ["Preto", "Branco", "Preto e prata"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 5, max: 35 }, female: { min: 5, max: 30 } },
    classification: ["Companhia", "Guarda"],
    description: "O Schnauzer é um cão versátil que varia de tamanho (Miniatura, Standard e Gigante). Inteligente, alerta e leal, é excelente cão de guarda. Adapta-se bem a apartamentos no caso do Schnauzer Miniatura, mas precisa de exercícios regulares."
  },
  {
    id: 42,
    slug: "basset-hound",
    breed: "Basset Hound",
    image: "v1777845014/dogs/ypjaa9ygvn9iksyjcaop.jpg",
    size: "Médio",
    countryOrigin: "França",
    colors: ["Tricolor", "Marrom e branco", "Preto e branco"],
    lifeExpectancy: { min: 10, max: 12 },
    adultWeightKg: { male: { min: 23, max: 29 }, female: { min: 20, max: 25 } },
    classification: ["Caça", "Companhia"],
    description: "Com orelhas longas e corpo alongado, o Basset é calmo, afetuoso e excelente farejador. Vive bem em apartamentos, mas precisa de caminhadas para evitar obesidade."
  },
  {
    id: 43,
    slug: "chow-chow",
    breed: "Chow Chow",
    image: "v1777845022/dogs/rvymwjliayxvbhm88cse.jpg",
    size: "Médio",
    countryOrigin: "China",
    colors: ["Vermelho", "Preto", "Azul", "Marrom", "Bege"],
    lifeExpectancy: { min: 9, max: 15 },
    adultWeightKg: { male: { min: 25, max: 32 }, female: { min: 20, max: 27 } },
    classification: ["Companhia", "Guarda"],
    description: "Independente, territorial e com aparência de leão, o Chow Chow é reservado com estranhos. Precisa de socialização precoce e não tolera bem o calor."
  },
  {
    id: 44,
    slug: "jack-russell-terrier",
    breed: "Jack Russell Terrier",
    image: "v1777845033/dogs/abz40io77vfv0l9y9bcb.jpg",
    size: "Pequeno",
    countryOrigin: "Reino Unido",
    colors: ["Branco", "Marrom e branco", "Tricolor"],
    lifeExpectancy: { min: 13, max: 16 },
    adultWeightKg: { male: { min: 6, max: 8 }, female: { min: 5, max: 7 } },
    classification: ["Caça", "Companhia"],
    description: "Enérgico, corajoso e muito esperto, o Jack Russell precisa de bastante exercício. Ideal para tutores ativos que gostem de aventuras."
  },
  {
    id: 45,
    slug: "newfoundland",
    breed: "Newfoundland (Terra Nova)",
    image: "v1777845037/dogs/vrdq8ryhnur0stvbsele.jpg",
    size: "Grande",
    countryOrigin: "Canadá",
    colors: ["Preto", "Marrom", "Cinza", "Preto e branco"],
    lifeExpectancy: { min: 8, max: 10 },
    adultWeightKg: { male: { min: 60, max: 70 }, female: { min: 45, max: 55 } },
    classification: ["Resgate", "Companhia"],
    description: "Gentil gigante, excelente nadador e protetor de crianças. Precisa de espaço amplo e não se adapta bem ao calor. Requer escovação frequente."
  },
  {
    id: 46,
    slug: "shiba-inu",
    breed: "Shiba Inu",
    image: "v1777845049/dogs/i2nccxs3uf0coeejkx2d.jpg",
    size: "Médio",
    countryOrigin: "Japão",
    colors: ["Vermelho", "Preto", "Branco", "Marrom"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 9, max: 10 }, female: { min: 8, max: 9 } },
    classification: ["Companhia"],
    description: "O Shiba Inu é um cão japonês, conhecido por sua aparência de raposa, personalidade independente e leal. Ele é inteligente e pode ser reservado com estranhos, mas é muito apegado à família. Adapta-se bem a apartamentos, desde que tenha exercícios e estímulo mental frequentes."
  },
  {
    id: 47,
    slug: "papillon",
    breed: "Papillon (Spaniel Anão Francês)",
    image: "v1777845039/dogs/ozpxxkiodkvoer9akqla.jpg",
    size: "Pequeno",
    countryOrigin: "França",
    colors: ["Preto e branco", "Marrom e branco", "Tricolor"],
    lifeExpectancy: { min: 12, max: 16 },
    adultWeightKg: { male: { min: 3, max: 4 }, female: { min: 3, max: 4 } },
    classification: ["Companhia"],
    description: "O Papillon é um cão pequeno e elegante, conhecido por suas orelhas em forma de borboleta. É inteligente, sociável e se adapta bem a apartamentos, desde que tenha exercícios e estímulo mental frequentes."
  },
  {
    id: 48,
    slug: "samoieda",
    breed: "Samoieda",
    image: "v1777845047/dogs/bvzqfxtntlg8yw0zzbpk.jpg",
    size: "Grande",
    countryOrigin: "Rússia",
    colors: ["Branco", "Bege"],
    lifeExpectancy: { min: 12, max: 14 },
    adultWeightKg: { male: { min: 25, max: 30 }, female: { min: 20, max: 25 } },
    classification: ["Companhia", "Trabalho"],
    description: "A Samoieda é um cão de porte grande, conhecida por sua pelagem densa e seu famoso 'sorriso'. É inteligente, leal e sociável, adaptando-se bem a ambientes frios. Precisa de exercícios diários e escovação frequente."
  },
  {
    id: 49,
    slug: "pastor-australiano",
    breed: "Pastor Australiano",
    image: "v1777845040/dogs/pxc2zpdvceixhpzrost1.jpg",
    size: "Grande",
    countryOrigin: "Estados Unidos",
    colors: ["Tricolor", "Preto e branco", "Branco e vermelho", "Azul", "Vermelho"],
    lifeExpectancy: { min: 12, max: 15 },
    adultWeightKg: { male: { min: 25, max: 32 }, female: { min: 18, max: 25 } },
    classification: ["Companhia", "Pastoreio"],
    description: "O Pastor Australiano é um cão extremamente inteligente, energético e leal. Apesar do nome, foi desenvolvido nos Estados Unidos para pastoreio. Excelente para esportes caninos, precisa de muito exercício e estímulo mental diariamente."
  },
  {
    id: 50,
    slug: "basenji",
    breed: "Basenji",
    image: "v1777845013/dogs/vttwzaefhewbrp8l2xmk.jpg",
    size: "Médio",
    countryOrigin: "Congo",
    colors: ["Tigrado", "Preto", "Branco", "Marrom"],
    lifeExpectancy: { min: 12, max: 14 },
    adultWeightKg: { male: { min: 10, max: 12 }, female: { min: 9, max: 11 } },
    classification: ["Companhia"],
    description: "O Basenji é conhecido como o 'cão que não late', emitindo um som peculiar parecido com um yodel. É independente, limpo (comportamento de gato) e curioso. Precisa de exercícios e tem forte instinto de caça."
  }
];