export type Size = 'Pequeno' | 'Médio' | 'Grande';

export type DogData = {
  id: number;
  breed: string;
  image: string;
  size: Size;
  countryOrigin: string;
  colors: string[];
  lifeExpectancy: string;
  adultWeightKg: { male: string; female: string };
  classification: string[];
  description: string;
};

export const dogsData: DogData[] = [
  {
    id: 1,
    breed: "Labrador Retriever",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845035/dogs/ayp1ygq1vzx0ksgtnzyk.jpg",
    size: "Médio",
    countryOrigin: "Canadá",
    colors: ["Preto", "Marrom", "Caramelo"],
    lifeExpectancy: "10 a 12 anos",
    adultWeightKg: { male: "29 a 36 kg", female: "25 a 32 kg" },
    classification: ["Companhia", "Assistência"],
    description: "O Labrador é dócil, brincalhão e inteligente, ideal para famílias ativas. Vive bem em casas com quintal e adora água e brincadeiras ao ar livre."
  },
  {
    id: 2,
    breed: "Golden Retriever",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845031/dogs/ayup8xovbrplcghurtwm.jpg",
    size: "Médio",
    countryOrigin: "Escócia",
    colors: ["Dourado"],
    lifeExpectancy: "10 a 12 anos",
    adultWeightKg: { male: "29 a 34 kg", female: "25 a 29 kg" },
    classification: ["Companhia", "Assistência"],
    description: "O Golden é afetuoso, calmo e excelente com crianças. Se adapta a espaços maiores e precisa de exercícios diários para manter a saúde física e mental."
  },
  {
    id: 3,
    breed: "Poodle",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845044/dogs/tnagugtzuwlulhg7fxng.jpg",
    size: "Pequeno",
    countryOrigin: "Alemanha/França",
    colors: ["Branco", "Preto", "Marrom", "Cinza", "Dourado", "Laranja"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "6 a 12 kg", female: "6 a 10 kg" },
    classification: ["Companhia", "Competições de agilidade"],
    description: "O Poodle é inteligente, hipoalergênico e aprende comandos com facilidade. Ideal para apartamentos, desde que tenha estímulos mentais e caminhadas regulares."
  },
  {
    id: 4,
    breed: "Bulldog Francês",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845018/dogs/tjv1geepxvp5vzbh66x0.jpg",
    size: "Pequeno",
    countryOrigin: "França",
    colors: ["Tigrado", "Preto", "Branco", "Cinza"],
    lifeExpectancy: "10 a 12 anos",
    adultWeightKg: { male: "9 a 14 kg", female: "8 a 12 kg" },
    classification: ["Companhia"],
    description: "Afetuoso e tranquilo, o Bulldog Francês adora companhia humana. Vive muito bem em apartamentos, mas exige atenção por causa de problemas respiratórios."
  },
  {
    id: 5,
    breed: "Bulldog Inglês",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845019/dogs/omqjp88dbd6earsgkov0.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Branco", "Caramelo", "Tigrado", "Vermelho"],
    lifeExpectancy: "8 a 10 anos",
    adultWeightKg: { male: "23 a 25 kg", female: "18 a 23 kg" },
    classification: ["Companhia"],
    description: "O Bulldog Inglês é calmo e companheiro, ideal para lares tranquilos. Adapta-se bem a apartamentos, mas requer cuidados com calor e exercícios leves."
  },
  {
    id: 6,
    breed: "Pastor Alemão",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845040/dogs/u58t4isbd98ounhgegpi.jpg",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Preto e marrom", "Cinza", "Preto"],
    lifeExpectancy: "9 a 13 anos",
    adultWeightKg: { male: "30 a 40 kg", female: "22 a 32 kg" },
    classification: ["Guarda", "Resgate", "Companhia"],
    description: "Leal, protetor e inteligente, o Pastor Alemão é excelente para guarda e resgate. Precisa de espaço e atividades, sendo mais adequado a casas com quintal ou áreas abertas."
  },
  {
    id: 7,
    breed: "Beagle",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845015/dogs/f2fndkclntjsjcy2ru6u.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Marrom", "Branco", "Preto", "Tricolor"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "10 a 14 kg", female: "9 a 12 kg" },
    classification: ["Caça", "Companhia"],
    description: "O Beagle é curioso, sociável e enérgico. Se adapta a casas e apartamentos com rotina ativa, mas requer atenção por seu faro aguçado e tendência a fugir."
  },
  {
    id: 8,
    breed: "Rottweiler",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845046/dogs/h9rut6q2arts9kqa3m1y.jpg",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Preto e marrom"],
    lifeExpectancy: "8 a 10 anos",
    adultWeightKg: { male: "50 a 60 kg", female: "35 a 48 kg" },
    classification: ["Guarda", "Companhia"],
    description: "O Rottweiler é forte, leal e protetor. Ideal para casas com espaço e donos experientes; precisa de socialização e adestramento desde cedo."
  },
  {
    id: 9,
    breed: "Yorkshire Terrier",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845054/dogs/nkbb6lt2nzedh1bigtba.jpg",
    size: "Pequeno",
    countryOrigin: "Reino Unido",
    colors: ["Cinza", "Dourado", "Preto"],
    lifeExpectancy: "13 a 16 anos",
    adultWeightKg: { male: "2 a 3 kg", female: "2 a 3 kg" },
    classification: ["Companhia"],
    description: "Pequeno, valente e elegante, o Yorkshire é ótimo para apartamentos. Precisa de escovação frequente e adora estar no colo do tutor."
  },
  {
    id: 10,
    breed: "Shih Tzu",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845050/dogs/ijrsu1i5tdvwl8fgi9wk.jpg",
    size: "Pequeno",
    countryOrigin: "China",
    colors: ["Branco", "Marrom", "Preto", "Dourado", "Cinza"],
    lifeExpectancy: "10 a 16 anos",
    adultWeightKg: { male: "4 a 7 kg", female: "4 a 7 kg" },
    classification: ["Companhia"],
    description: "O Shih Tzu é dócil, sociável e muito apegado à família. Ideal para apartamentos, exige cuidados com os pelos e olhos sensíveis."
  },
  {
    id: 11,
    breed: "Border Collie",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845016/dogs/mwsvbrhp7mayo5njg0g3.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Preto e branco", "Merle", "Tricolor", "Marrom e branco"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "16 a 20 kg", female: "14 a 18 kg" },
    classification: ["Assistência", "Companhia"],
    description: "Extremamente inteligente e ágil, o Border Collie é ideal para quem mora no campo ou tem espaço para atividades intensas. Não se adapta bem à vida sedentária."
  },
  {
    id: 12,
    breed: "Dachshund",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845024/dogs/xvi8qjmi9retqo6y7ttl.jpg",
    size: "Pequeno",
    countryOrigin: "Alemanha",
    colors: ["Marrom", "Preto e marrom", "Vermelho", "Tigrado"],
    lifeExpectancy: "12 a 16 anos",
    adultWeightKg: { male: "7 a 14 kg", female: "7 a 12 kg" },
    classification: ["Caça", "Companhia"],
    description: "Destemido e divertido, o Dachshund adora cavar e seguir trilhas. Vive bem em apartamentos, mas precisa de cuidados com a coluna e caminhadas leves."
  },
  {
    id: 13,
    breed: "Boxer",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845018/dogs/tjv1geepxvp5vzbh66x0.jpg",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Caramelo", "Tigrado", "Branco"],
    lifeExpectancy: "10 a 12 anos",
    adultWeightKg: { male: "28 a 32 kg", female: "25 a 29 kg" },
    classification: ["Guarda", "Companhia"],
    description: "O Boxer é brincalhão, fiel e cheio de energia. Ideal para casas com quintal e tutores que gostam de atividades ao ar livre."
  },
  {
    id: 14,
    breed: "Doberman",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845025/dogs/qefokvlrtl0b2mpu7fth.webp",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Preto e marrom", "Marrom", "Azul", "Isabela"],
    lifeExpectancy: "10 a 13 anos",
    adultWeightKg: { male: "40 a 45 kg", female: "30 a 35 kg" },
    classification: ["Guarda", "Companhia"],
    description: "Elegante, protetor e obediente, o Doberman é ótimo para guarda. Requer espaço, liderança firme e atenção constante."
  },
  {
    id: 15,
    breed: "Husky Siberiano",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845032/dogs/add7zxqilp9rhm7hrg9o.jpg",
    size: "Grande",
    countryOrigin: "Rússia",
    colors: ["Cinza", "Preto e branco", "Vermelho", "Branco"],
    lifeExpectancy: "12 a 14 anos",
    adultWeightKg: { male: "23 a 27 kg", female: "16 a 23 kg" },
    classification: ["Companhia", "Competições de agilidade"],
    description: "Independente e energético, o Husky adora correr e é sensível ao calor. Prefere ambientes frios e espaços amplos, como casas com quintal."
  },
  {
    id: 16,
    breed: "Chihuahua",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845021/dogs/khtfa4v5tigcpmpv2wty.png",
    size: "Pequeno",
    countryOrigin: "México",
    colors: ["Marrom", "Preto", "Branco", "Dourado", "Mesclado"],
    lifeExpectancy: "14 a 17 anos",
    adultWeightKg: { male: "1,5 a 3 kg", female: "1,5 a 3 kg" },
    classification: ["Companhia"],
    description: "Pequeno e alerta, o Chihuahua é ideal para apartamentos e tutores tranquilos. Gosta de colo, mas pode ser desconfiado com estranhos."
  },
  {
    id: 17,
    breed: "Pug",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845045/dogs/qfg3ag8uyoskzjogqf0t.jpg",
    size: "Pequeno",
    countryOrigin: "China",
    colors: ["Caramelo", "Preto", "Cinza", "Abricot"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "6 a 9 kg", female: "6 a 8 kg" },
    classification: ["Companhia"],
    description: "Afetuoso e divertido, o Pug é perfeito para apartamentos. Requer atenção com a respiração e não tolera muito calor ou exercícios intensos."
  },
  {
    id: 18,
    breed: "Vira-lata",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845051/dogs/c8k2o3wxbcfrfzzolqbp.jpg",
    size: "Médio",
    countryOrigin: "Brasil",
    colors: ["Preto", "Caramelo", "Branco", "Mesclado"],
    lifeExpectancy: "12 a 16 anos",
    adultWeightKg: { male: "12 a 25 kg", female: "10 a 20 kg" },
    classification: ["Companhia", "Guarda"],
    description: "Versátil, resistente e amoroso, o Vira-lata se adapta bem a diferentes ambientes. Cada um tem uma personalidade única, ideal para quem busca um companheiro fiel."
  },
  {
    id: 19,
    breed: "Cocker Spaniel",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845023/dogs/zzmfzzu4vxe3g4yvf7pd.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Dourado", "Preto", "Marrom", "Tricolor", "Azul ruão"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "13 a 15 kg", female: "12 a 14 kg" },
    classification: ["Caça", "Companhia"],
    description: "Meigo e sociável, o Cocker é ótimo para crianças e vive bem em apartamentos ou casas. Precisa de escovação frequente e passeios diários."
  },
  {
    id: 20,
    breed: "Maltês",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845037/dogs/oflbmfefmihc4368eni7.jpg",
    size: "Pequeno",
    countryOrigin: "Itália",
    colors: ["Branco"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "3 a 4 kg", female: "3 a 4 kg" },
    classification: ["Companhia"],
    description: "Delicado e muito apegado, o Maltês se adapta bem a apartamentos. Seus pelos exigem escovação constante, e ele adora colo e atenção."
  },
  {
    id: 21,
    breed: "Fila Brasileiro",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845028/dogs/g6sxqi5tbanlosdm5kx0.jpg",
    size: "Grande",
    countryOrigin: "Brasil",
    colors: ["Caramelo", "Tigrado", "Preto"],
    lifeExpectancy: "9 a 11 anos",
    adultWeightKg: { male: "50 a 60 kg", female: "40 a 50 kg" },
    classification: ["Guarda", "Caça"],
    description: "Imponente e territorialista, o Fila exige espaço, adestramento e socialização. Ideal para grandes propriedades e tutores experientes."
  },
  {
    id: 22,
    breed: "Fox Paulistinha",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845030/dogs/iambjenav85rkzoucy9u.jpg",
    size: "Médio",
    countryOrigin: "Brasil",
    colors: ["Tricolor"],
    lifeExpectancy: "13 a 16 anos",
    adultWeightKg: { male: "7 a 10 kg", female: "6 a 9 kg" },
    classification: ["Companhia", "Competições de agilidade"],
    description: "Ágil, leal e muito esperto, o Fox Paulistinha é ótimo para quem vive em casas ou apartamentos com rotina ativa. Ama brincar e aprender truques."
  },
  {
    id: 23,
    breed: "Spitz Alemão (Lulu da Pomerânia)",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845051/dogs/xptptpmpblwknxdulvnw.jpg",
    size: "Pequeno",
    countryOrigin: "Alemanha",
    colors: ["Laranja", "Branco", "Preto", "Marrom", "Creme"],
    lifeExpectancy: "12 a 16 anos",
    adultWeightKg: { male: "1,5 a 3,5 kg", female: "1,5 a 3 kg" },
    classification: ["Companhia"],
    description: "Pequeno, animado e muito apegado ao tutor, o Spitz Alemão é ideal para apartamentos. Gosta de atenção e cuidados com os pelos são essenciais para manter sua beleza."
  },
  {
    id: 24,
    breed: "Pitbull Terrier Americano",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845043/dogs/ppchqueeqszgswvdsqj9.jpg",
    size: "Médio",
    countryOrigin: "Estados Unidos",
    colors: ["Preto", "Branco", "Caramelo", "Tigrado", "Cinza"],
    lifeExpectancy: "12 a 14 anos",
    adultWeightKg: { male: "16 a 30 kg", female: "14 a 27 kg" },
    classification: ["Companhia", "Guarda"],
    description: "Forte, leal e inteligente, o Pitbull é um excelente companheiro para tutores firmes e ativos. Requer socialização desde cedo e vive melhor em casas com espaço para se exercitar."
  },
  {
    id: 25,
    breed: "Dálmata",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845025/dogs/wul8nde3xpkcymggifd2.png",
    size: "Médio",
    countryOrigin: "Croácia",
    colors: ["Preto e branco", "Branco e marrom"],
    lifeExpectancy: "10 a 13 anos",
    adultWeightKg: { male: "24 a 32 kg", female: "22 a 28 kg" },
    classification: ["Companhia", "Guarda", "Caça"],
    description: "O Dálmata é um cão enérgico e extrovertido, famoso por sua pelagem manchada. Ele é excelente para famílias ativas e precisa de bastante exercício para se manter saudável e feliz. Seu instinto protetor e lealdade fazem dele um ótimo companheiro."
  },
  {
    id: 26,
    breed: "Lhasa Apso",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845036/dogs/mmknefnihqgfnq5yg40o.jpg",
    size: "Pequeno",
    countryOrigin: "China",
    colors: ["Dourado", "Preto", "Branco", "Mesclado", "Cinza"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "6 a 8 kg", female: "5 a 7 kg" },
    classification: ["Companhia"],
    description: "Independente, calmo e protetor, o Lhasa Apso vive muito bem em apartamentos. Exige escovação frequente e costuma ser reservado com estranhos."
  },
  {
    id: 27,
    breed: "Akita Inu",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845012/dogs/olbccr7nmnic9wfczbke.jpg",
    size: "Grande",
    countryOrigin: "Japão",
    colors: ["Vermelho", "Branco", "Tigrado", "Gergelim"],
    lifeExpectancy: "10 a 13 anos",
    adultWeightKg: { male: "40 a 50 kg", female: "30 a 40 kg" },
    classification: ["Guarda", "Companhia"],
    description: "Silencioso, fiel e imponente, o Akita Inu é indicado para tutores experientes. Vive melhor em locais espaçosos e com socialização adequada desde filhote."
  },
  {
    id: 28,
    breed: "Cão de Crista Chinês",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845020/dogs/hos0wqhcwzifzdig1rsy.jpg",
    size: "Pequeno",
    countryOrigin: "China",
    colors: ["Rosa", "Cinza", "Preto", "Branco", "Manchado"],
    lifeExpectancy: "13 a 15 anos",
    adultWeightKg: { male: "3 a 6 kg", female: "3 a 5 kg" },
    classification: ["Companhia"],
    description: "Exótico, brincalhão e afetuoso, o Cão de Crista Chinês é ideal para apartamentos e lares tranquilos. Exige cuidados com a pele, principalmente se for da variedade sem pelos."
  },
  {
    id: 29,
    breed: "Weimaraner",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845052/dogs/i10u5rtmlnyfb9wdaniq.jpg",
    size: "Grande",
    countryOrigin: "Alemanha",
    colors: ["Cinza-prateado"],
    lifeExpectancy: "10 a 13 anos",
    adultWeightKg: { male: "30 a 40 kg", female: "25 a 35 kg" },
    classification: ["Caça", "Companhia"],
    description: "Elegante, atlético e inteligente, o Weimaraner precisa de muito exercício e estímulo mental. Vive melhor em casas com quintal e com tutores ativos."
  },
  {
    id: 30,
    breed: "São Bernardo",
    image: 'https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845047/dogs/nh8ycc3fnuh9erkwkdy8.jpg',
    size: 'Grande',
    countryOrigin: 'Suíça',
    colors: ['Branco e marrom', 'Branco e vermelho', 'Tigrado'],
    lifeExpectancy: '8 a 10 anos',
    adultWeightKg: { male: "65 a 80 kg", female: "55 a 70 kg" },
    classification: ['Guarda', 'Companhia', 'Resgate'],
    description: "Gentil, paciente e protetor, o São Bernardo é ideal para casas espaçosas ou zonas rurais. Apesar do tamanho imponente, é excelente com crianças, mas precisa de espaço, escovação regular e atenção ao calor."
  },
  {
    id: 31,
    breed: "Pastor Belga",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845041/dogs/fpeaz81xmzlsjpzgkem2.jpg",
    size: "Grande",
    countryOrigin: "Bélgica",
    colors: ["Preto", "Marrom", "Tigrado"],
    lifeExpectancy: "12 a 14 anos",
    adultWeightKg: { male: "25 a 30 kg", female: "25 a 30 kg" },
    classification: ["Guarda", "Trabalho"],
    description: "O Pastor Belga é ágil, inteligente e muito leal. Usado em forças policiais, exige atividades físicas e mentais diárias."
  },
  {
    id: 32,
    breed: "Pinscher Miniatura",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845042/dogs/pw8tgfyaapkj7zp3bbst.jpg",
    size: "Pequeno",
    countryOrigin: "Alemanha",
    colors: ["Preto e castanho", "Marrom", "Caramelo"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "3 a 5 kg", female: "3 a 5 kg" },
    classification: ["Companhia"],
    description: "Valente e energético, o Pinscher é um ótimo cão de alerta. Requer socialização desde filhote para evitar comportamento agressivo."
  },
  {
    id: 33,
    breed: "Dogo Argentino",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845027/dogs/ocxto7elivpuoaj23seh.jpg",
    size: "Grande",
    countryOrigin: "Argentina",
    colors: ["Branco"],
    lifeExpectancy: "10 a 12 anos",
    adultWeightKg: { male: "40 a 45 kg", female: "40 a 45 kg" },
    classification: ["Caça", "Guarda"],
    description: "O Dogo Argentino é uma raça forte e atlética, criada originalmente na Argentina para caça de animais grandes como javalis. É corajoso, leal e protetor, exigindo um tutor experiente, com socialização e adestramento desde cedo. Apesar de sua aparência intimidadora, pode ser afetuoso com a família."
  },
  {
    id: 34,
    breed: "Boston Terrier",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845017/dogs/evpdnubtib7tbtxn57ay.jpg",
    size: "Pequeno",
    countryOrigin: "Estados Unidos",
    colors: ["Preto e branco", "Tigrado", "Marrom e branco"],
    lifeExpectancy: "11 a 13 anos",
    adultWeightKg: { male: "8 a 11 kg", female: "6 a 9 kg" },
    classification: ["Companhia"],
    description: "Afetuoso, brincalhão e sociável, o Boston Terrier se adapta bem a apartamentos e é ideal para famílias."
  },
  {
    id: 35,
    breed: "Boiadeiro Australiano",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845015/dogs/ywg5ikjrpnziaactcjqs.jpg",
    size: "Médio",
    countryOrigin: "Austrália",
    colors: ["Azul", "Vermelho"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "16 a 22 kg", female: "14 a 20 kg" },
    classification: ["Pastoreio", "Caça"],
    description: "Ágil, inteligente e muito resistente, o Boiadeiro Australiano é excelente para atividades no campo e esportes caninos."
  },
  {
    id: 36,
    breed: "Cane Corso",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845020/dogs/eeibgmcobcwceihwnnmz.jpg",
    size: "Grande",
    countryOrigin: "Itália",
    colors: ["Preto", "Cinza", "Tigrado", "Marrom"],
    lifeExpectancy: "9 a 12 anos",
    adultWeightKg: { male: "45 a 50 kg", female: "40 a 45 kg" },
    classification: ["Guarda"],
    description: "Robusto e protetor, o Cane Corso é fiel à sua família. Precisa de adestramento firme e bastante espaço."
  },
  {
    id: 37,
    breed: "Shar Pei",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845049/dogs/hs0kqxtcqul3fxmwcu1e.jpg",
    size: "Médio",
    countryOrigin: "China",
    colors: ["Bege", "Preto", "Marrom", "Azul"],
    lifeExpectancy: "8 a 12 anos",
    adultWeightKg: { male: "20 a 25 kg", female: "18 a 23 kg" },
    classification: ["Companhia"],
    description: "Com rugas marcantes e personalidade reservada, o Shar Pei é calmo e fiel, mas precisa de socialização desde cedo."
  },
  {
    id: 38,
    breed: "Kangal",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845033/dogs/n5opwfhufvvlk2vbpsaq.jpg",
    size: "Grande",
    countryOrigin: "Turquia",
    colors: ["Cinza", "Bege", "Amarelo", "Preto"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "50 a 66 kg", female: "40 a 55 kg" },
    classification: ["Guarda", "Caça", "Pastoreio"],
    description: "O Kangal é uma raça originária da Turquia, conhecida por sua força, coragem e instinto protetor. Tradicionalmente usado para proteger rebanhos, é extremamente leal à sua família. Apesar de seu tamanho imponente, é calmo, equilibrado e gentil."
  },
  {
    id: 39,
    breed: "Whippet",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845053/dogs/xlqyiujkvzdasme9jtqe.jpg",
    size: "Médio",
    countryOrigin: "Reino Unido",
    colors: ["Preto", "Branco", "Tigrado", "Cinza", "Preto e branco"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "12 a 15 kg", female: "10 a 14 kg" },
    classification: ["Corrida", "Companhia"],
    description: "Rápido, sensível e elegante, o Whippet é ótimo para quem quer um cão calmo em casa, mas com energia para correr ao ar livre."
  },
  {
    id: 40,
    breed: "Ovelheiro Gaúcho",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845038/dogs/yrbxlp5uuudl38exhsyi.jpg",
    size: "Grande",
    countryOrigin: "Brasil",
    colors: ["Preto", "Branco", "Cinza", "Azul", "Tricolor"],
    lifeExpectancy: "13 a 15 anos",
    adultWeightKg: { male: "30 a 40 kg", female: "25 a 35 kg" },
    classification: ["Pastoreio", "Guarda", "Companhia"],
    description: "O Ovelheiro Gaúcho é uma raça brasileira, conhecida por sua inteligência, energia e forte instinto de pastoreio. Adaptado ao clima do sul do Brasil, é resistente, leal e excelente para trabalhar com rebanhos. Sociável com a família, mas pode ser reservado com estranhos."
  },
  {
    id: 41,
    breed: "Schnauzer",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845048/dogs/fdrkuwwlgjutwioses34.jpg",
    size: "Médio",
    countryOrigin: "Alemanha",
    colors: ["Preto", "Sal e pimenta", "Branco", "Preto e prata"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "5 a 35 kg", female: "5 a 30 kg" },
    classification: ["Companhia", "Guarda"],
    description: "O Schnauzer é um cão versátil que varia de tamanho (Miniatura, Standard e Gigante). Inteligente, alerta e leal, é excelente cão de guarda. Adapta-se bem a apartamentos no caso do Schnauzer Miniatura, mas precisa de exercícios regulares."
  },
  {
    id: 42,
    breed: "Basset Hound",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845014/dogs/ypjaa9ygvn9iksyjcaop.jpg",
    size: "Médio",
    countryOrigin: "França",
    colors: ["Tricolor", "Branco e marrom", "Preto e branco"],
    lifeExpectancy: "10 a 12 anos",
    adultWeightKg: { male: "23 a 29 kg", female: "20 a 25 kg" },
    classification: ["Caça", "Companhia"],
    description: "Com orelhas longas e corpo alongado, o Basset é calmo, afetuoso e excelente farejador. Vive bem em apartamentos, mas precisa de caminhadas para evitar obesidade."
  },
  {
    id: 43,
    breed: "Chow Chow",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845022/dogs/rvymwjliayxvbhm88cse.jpg",
    size: "Médio",
    countryOrigin: "China",
    colors: ["Vermelho", "Preto", "Azul", "Canela", "Creme"],
    lifeExpectancy: "9 a 15 anos",
    adultWeightKg: { male: "25 a 32 kg", female: "20 a 27 kg" },
    classification: ["Companhia", "Guarda"],
    description: "Independente, territorial e com aparência de leão, o Chow Chow é reservado com estranhos. Precisa de socialização precoce e não tolera bem o calor."
  },
  {
    id: 44,
    breed: "Jack Russell Terrier",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845033/dogs/abz40io77vfv0l9y9bcb.jpg",
    size: "Pequeno",
    countryOrigin: "Reino Unido",
    colors: ["Branco", "Branco e marrom", "Tricolor"],
    lifeExpectancy: "13 a 16 anos",
    adultWeightKg: { male: "6 a 8 kg", female: "5 a 7 kg" },
    classification: ["Caça", "Companhia"],
    description: "Enérgico, corajoso e muito esperto, o Jack Russell precisa de bastante exercício. Ideal para tutores ativos que gostem de aventuras."
  },
  {
    id: 45,
    breed: "Newfoundland (Terra Nova)",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845037/dogs/vrdq8ryhnur0stvbsele.jpg",
    size: "Grande",
    countryOrigin: "Canadá",
    colors: ["Preto", "Marrom", "Cinza", "Preto e branco"],
    lifeExpectancy: "8 a 10 anos",
    adultWeightKg: { male: "60 a 70 kg", female: "45 a 55 kg" },
    classification: ["Resgate", "Companhia"],
    description: "Gentil gigante, excelente nadador e protetor de crianças. Precisa de espaço amplo e não se adapta bem ao calor. Requer escovação frequente."
  },
  {
    id: 46,
    breed: "Shiba Inu",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845049/dogs/i2nccxs3uf0coeejkx2d.jpg",
    size: "Médio",
    countryOrigin: "Japão",
    colors: ["Vermelho", "Preto", "Branco", "Canela"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "9 a 10 kg", female: "8 a 9 kg" },
    classification: ["Companhia"],
    description: "O Shiba Inu é um cão japonês, conhecido por sua aparência de raposa, personalidade independente e leal. Ele é inteligente e pode ser reservado com estranhos, mas é muito apegado à família. Adapta-se bem a apartamentos, desde que tenha exercícios e estímulo mental frequentes."
  },
  {
    id: 47,
    breed: "Papillon (Spaniel Anão Francês)",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845039/dogs/ozpxxkiodkvoer9akqla.jpg",
    size: "Pequeno",
    countryOrigin: "França",
    colors: ["Preto e branco", "Branco e marrom", "Tricolor"],
    lifeExpectancy: "12 a 16 anos",
    adultWeightKg: { male: "3 a 4 kg", female: "3 a 4 kg" },
    classification: ["Companhia"],
    description: "O Papillon é um cão pequeno e elegante, conhecido por suas orelhas em forma de borboleta. É inteligente, sociável e se adapta bem a apartamentos, desde que tenha exercícios e estímulo mental frequentes."
  },
  {
    id: 48,
    breed: "Samoieda",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845047/dogs/bvzqfxtntlg8yw0zzbpk.jpg",
    size: "Grande",
    countryOrigin: "Rússia",
    colors: ["Branco", "Creme"],
    lifeExpectancy: "12 a 14 anos",
    adultWeightKg: { male: "25 a 30 kg", female: "20 a 25 kg" },
    classification: ["Companhia", "Trabalho"],
    description: "A Samoieda é um cão de porte grande, conhecida por sua pelagem densa e seu famoso 'sorriso'. É inteligente, leal e sociável, adaptando-se bem a ambientes frios. Precisa de exercícios diários e escovação frequente."
  },
  {
    id: 49,
    breed: "Pastor Australiano",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845040/dogs/pxc2zpdvceixhpzrost1.jpg",
    size: "Grande",
    countryOrigin: "Estados Unidos",
    colors: ["Tricolor", "Preto e branco", "Vermelho e branco", "Azul merle", "Vermelho merle"],
    lifeExpectancy: "12 a 15 anos",
    adultWeightKg: { male: "25 a 32 kg", female: "18 a 25 kg" },
    classification: ["Companhia", "Pastoreio"],
    description: "O Pastor Australiano é um cão extremamente inteligente, energético e leal. Apesar do nome, foi desenvolvido nos Estados Unidos para pastoreio. Excelente para esportes caninos, precisa de muito exercício e estímulo mental diariamente."
  },
  {
    id: 50,
    breed: "Basenji",
    image: "https://res.cloudinary.com/dvuxplf3j/image/upload/v1777845013/dogs/vttwzaefhewbrp8l2xmk.jpg",
    size: "Médio",
    countryOrigin: "Congo",
    colors: ["Tigrado", "Preto", "Branco", "Marrom"],
    lifeExpectancy: "12 a 14 anos",
    adultWeightKg: { male: "10 a 12 kg", female: "9 a 11 kg" },
    classification: ["Companhia"],
    description: "O Basenji é conhecido como o 'cão que não late', emitindo um som peculiar parecido com um yodel. É independente, limpo (comportamento de gato) e curioso. Precisa de exercícios e tem forte instinto de caça."
  }
];